name: Scrape price 

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '*/10 * * * *'

permissions:
  contents: write 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install env
      run: pip install -r requirements.txt 
    - name: Scrape
      run: python scrape.py
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add prices.csv
        git commit -m "Add new" || exit 0 
        git pull --rebase 
        git push