name: Scrape price 

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 0 */7 * *'

permissions:
  contents: write 

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Decode secret
      run: |
        echo "${{ secrets.SERVICE_ACCOUNT }}" | base64 -d > secret.json
    - name: Scrape
      run: sh scrape.sh